### ISSUE TITLE
Error thrown when running snakemake era5_return --cores 9

### ISSUE THREAD

**Issue by zhaowilliam** [jdossgollin/2021-TXtreme#2]
Firrst follow the directions to set up the environment and the library, then use command: 
touch scripts/*.py
snakemake --cores 3
to re-run everything. However, the running is interrupted in era5_return.

```
Error:
0%|                                                                                                                                 | 0/65 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/burg/glab/users/wz2481/testpy/2021-TXtreme/scripts/era5_return.py", line 68, in <module>
    main()
  File "/burg/glab/users/wz2481/testpy/2021-TXtreme/scripts/era5_return.py", line 59, in main
    rt_estimate = cold_return_period(hdd_21, hdd_obs)
  File "/burg/glab/users/wz2481/testpy/2021-TXtreme/codebase/calc.py", line 45, in cold_return_period
    return return_period(-y, -x)
  File "/burg/glab/users/wz2481/testpy/2021-TXtreme/codebase/calc.py", line 26, in return_period
    theta = gev.fit(x, 0, loc=40, scale=10, optimizer=optimizer)
  File "/burg/home/wz2481/.conda/envs/txtreme/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py", line 2497, in fit
    obj = func(vals, data)
  File "/burg/home/wz2481/.conda/envs/txtreme/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py", line 2239, in _penalized_nnlf
    return self._nnlf_and_penalty(x, args) + n_log_scale
  File "/burg/home/wz2481/.conda/envs/txtreme/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py", line 2218, in _nnlf_and_penalty
    if n_bad > 0:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**Comment by jdossgollin** [comment]
Looks like it's having some trouble fitting the GEV distribution. It would be helpful to see what is going on inside your `return_period` function in `codebase/calc.py`. For example, if you add `print(x) before the `GEV.fit` line, what do you get?
Just want to rule out that the data isn't getting read in

**Comment by zhaowilliam** [comment]
Thanks a lot @jdossgollin .  I add the print(x) before the GEV.fit` line. Then get:

CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.


Defaulting to user installation because normal site-packages is not writeable
Obtaining file:///burg/glab/users/wz2481/testpy/2021-TXtreme
Installing collected packages: codebase
  Attempting uninstall: codebase
    Found existing installation: codebase 0.1
    Uninstalling codebase-0.1:
      Successfully uninstalled codebase-0.1
  Running setup.py develop for codebase
Successfully installed codebase-0.1
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 9
Rules claiming more threads will be scaled down.
Job stats:
job            count    min threads    max threads
-----------  -------  -------------  -------------
era5_return        1              1              1
total              1              1              1

Select jobs to execute...

[Sat Jan 22 06:34:20 2022]
rule era5_return:
    input: /burg/glab/users/wz2481/testpy/2021-TXtreme/scripts/era5_return.py, /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1950.nc, /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1951.nc, /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1952.nc, /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1953.nc, /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1954.nc, /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1955.nc, /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1956.nc, /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1957.nc, /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1958.nc, /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1959.nc, /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1960.nc, /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1961.nc, /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1962.nc, /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1963.nc, /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1964.nc, /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1965.nc, /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1966.nc, /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1967.nc, /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1968.nc, /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1969.nc, /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1970.nc, /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1971.nc, /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1972.nc, /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1973.nc, /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1974.nc, /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1975.nc, /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1976.nc, /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1977.nc, /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1978.nc, /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1979.nc, /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1980.nc, /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1981.nc, /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1982.nc, /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1983.nc, /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1984.nc, /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1985.nc, /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1986.nc, /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1987.nc, /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1988.nc, /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1989.nc, /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1990.nc, /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1991.nc, /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1992.nc, /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1993.nc, /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1994.nc, /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1995.nc, /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1996.nc, /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1997.nc, /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1998.nc, /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1999.nc, /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_2000.nc, /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_2001.nc, /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_2002.nc, /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_2003.nc, /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_2004.nc, /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_2005.nc, /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_2006.nc, /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_2007.nc, /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_2008.nc, /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_2009.nc, /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_2010.nc, /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_2011.nc, /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_2012.nc, /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_2013.nc, /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_2014.nc, /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_2015.nc, /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_2016.nc, /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_2017.nc, /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_2018.nc, /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_2019.nc, /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_2020.nc, /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_2021.nc
    output: /burg/glab/users/wz2481/testpy/2021-TXtreme/data/processed/era5/tx/return_period.nc
    jobid: 0
    resources: tmpdir=/tmp


  0%|          | 0/274 [00:00<?, ?it/s]
  0%|          | 0/274 [00:00<?, ?it/s]
[[-268.64337 -268.64337]
 [-273.7827  -273.7827 ]
 [-272.09106 -272.09106]
 [-268.4724  -268.4724 ]
 [-268.20248 -268.20248]
 [-271.51062 -271.51062]
 [-271.3359  -271.3359 ]
 [-270.65524 -270.65524]
 [-276.88727 -276.88727]
 [-272.63837 -272.63837]
 [-276.609   -276.609  ]
 [-277.3732  -277.3732 ]
 [-273.99374 -273.99374]
 [-273.79236 -273.79236]
 [-275.9585  -275.9585 ]
 [-269.69278 -269.69278]
 [-270.40588 -270.40588]
 [-274.77737 -274.77737]
 [-272.93842 -272.93842]
 [-268.84924 -268.84924]
 [-274.91006 -274.91006]
 [-267.08633 -267.08633]
 [-268.66364 -268.66364]
 [-274.0882  -274.0882 ]
 [-273.78198 -273.78198]
 [-273.28802 -273.28802]
 [-273.64124 -273.64124]
 [-275.3778  -275.3778 ]
 [-271.6607  -271.6607 ]
 [-274.5259  -274.5259 ]
 [-270.74933 -270.74933]
 [-272.4767  -272.4767 ]
 [-271.5244  -271.5244 ]
 [-277.60712 -277.60712]
 [-272.51633 -272.51633]
 [-269.91614 -269.91614]
 [-269.3391  -269.3391 ]
 [-277.05966 -277.05966]
 [-275.98886 -275.98886]
 [-264.0232  -264.0232 ]
 [-270.82455 -270.82455]
 [-270.99203 -270.99203]
 [-276.6563  -276.6563 ]
 [-269.93396 -269.93396]
 [-273.03012 -273.03012]
 [-272.8236  -272.8236 ]
 [-271.53516 -271.53516]
 [-268.3067  -268.3067 ]
 [-274.08615 -274.08615]
 [-274.3597  -274.3597 ]
 [-275.4527  -275.4527 ]
 [-274.55258 -274.55258]
 [-274.76498 -274.76498]
 [-277.24872 -277.24872]
 [-272.69504 -272.69504]
 [-273.4841  -273.4841 ]
 [-276.25687 -276.25687]
 [-273.70215 -273.70215]
 [-272.02676 -272.02676]
 [-271.75583 -271.75583]
 [-275.9392  -275.9392 ]
 [-270.35254 -270.35254]
 [-267.79578 -267.79578]
 [-276.39178 -276.39178]
 [-273.61465 -273.61465]
 [-278.01886 -278.01886]
 [-278.04462 -278.04462]
 [-273.4361  -273.4361 ]
 [-276.34494 -276.34494]
 [-269.86032 -269.86032]
 [-270.1313  -270.1313 ]]
Traceback (most recent call last):
  File "/burg/glab/users/wz2481/testpy/2021-TXtreme/scripts/era5_return.py", line 68, in <module>
    main()
  File "/burg/glab/users/wz2481/testpy/2021-TXtreme/scripts/era5_return.py", line 59, in main
    rt_estimate = cold_return_period(hdd_21, hdd_obs)
  File "/burg/glab/users/wz2481/testpy/2021-TXtreme/codebase/calc.py", line 46, in cold_return_period
    return return_period(-y, -x)
  File "/burg/glab/users/wz2481/testpy/2021-TXtreme/codebase/calc.py", line 27, in return_period
    theta = gev.fit(x, 0, loc=40, scale=10, optimizer=optimizer)
  File "/burg/opt/anaconda3-2021.11/lib/python3.9/site-packages/scipy/stats/_distn_infrastructure.py", line 2497, in fit
    obj = func(vals, data)
  File "/burg/opt/anaconda3-2021.11/lib/python3.9/site-packages/scipy/stats/_distn_infrastructure.py", line 2239, in _penalized_nnlf
    return self._nnlf_and_penalty(x, args) + n_log_scale
  File "/burg/opt/anaconda3-2021.11/lib/python3.9/site-packages/scipy/stats/_distn_infrastructure.py", line 2218, in _nnlf_and_penalty
    if n_bad > 0:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
[Sat Jan 22 06:55:24 2022]
Error in rule era5_return:
    jobid: 0
    output: /burg/glab/users/wz2481/testpy/2021-TXtreme/data/processed/era5/tx/return_period.nc
    shell:
        python /burg/glab/users/wz2481/testpy/2021-TXtreme/scripts/era5_return.py -i /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1950.nc /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1951.nc /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1952.nc /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1953.nc /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1954.nc /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1955.nc /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1956.nc /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1957.nc /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1958.nc /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1959.nc /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1960.nc /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1961.nc /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1962.nc /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1963.nc /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1964.nc /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1965.nc /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1966.nc /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1967.nc /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1968.nc /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1969.nc /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1970.nc /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1971.nc /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1972.nc /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1973.nc /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1974.nc /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1975.nc /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1976.nc /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1977.nc /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1978.nc /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1979.nc /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1980.nc /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1981.nc /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1982.nc /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1983.nc /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1984.nc /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1985.nc /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1986.nc /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1987.nc /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1988.nc /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1989.nc /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1990.nc /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1991.nc /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1992.nc /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1993.nc /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1994.nc /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1995.nc /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1996.nc /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1997.nc /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1998.nc /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_1999.nc /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_2000.nc /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_2001.nc /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_2002.nc /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_2003.nc /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_2004.nc /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_2005.nc /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_2006.nc /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_2007.nc /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_2008.nc /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_2009.nc /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_2010.nc /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_2011.nc /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_2012.nc /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_2013.nc /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_2014.nc /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_2015.nc /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_2016.nc /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_2017.nc /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_2018.nc /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_2019.nc /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_2020.nc /burg/glab/users/wz2481/testpy/2021-TXtreme/data/raw/era5/tx/temp_hourly_2021.nc -o /burg/glab/users/wz2481/testpy/2021-TXtreme/data/processed/era5/tx/return_period.nc
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /burg/glab/users/wz2481/testpy/2021-TXtreme/.snakemake/log/2022-01-22T063404.352046.snakemake.log

**Comment by jdossgollin** [comment]
Those sound like two different problems. The first is related to getting conda set up on the machine you are using.
